### ISSUE TITLE
Move our runners to aws_autoscaling, since we need a bit more RAM

### ISSUE THREAD

**Issue by martun** [NilFoundation/crypto3-zk#238]
After look-ups and Poseidon to the Placeholder proof-system are integrated into our code, our tests will require slightly more RAM (Probably 8 GB is enough for us). Our current runners have less, so we need to change the runners. To do that, we need to create a Dockerfile on which our test will run.

We have a naive infrastructure for self-hosted runners. It can be used to create a proper setup for auto-scalable self-hosted runners: https://github.com/NilFoundation/deployment-infrastructure

We need to write a Dockerfile, similar to [1](https://github.com/NilFoundation/crypto3-environment/blob/master/environment/Dockerfile) or [2](https://github.com/NilFoundation/proof-market/blob/master/scripts/docker/Dockerfile).

Then add a script like this:
https://github.com/NilFoundation/proof-market/blob/master/scripts/ci.sh

Use it in CI like this:
https://github.com/NilFoundation/proof-market/blob/master/.github/workflows/main.yml

Requirements for the autoscaling machines:

- Ubuntu 22.04 x86-64
- Mac x86
- Max M1
- Mac M2

Probably we need two types of machines basing on our RAM requirements:
- For zk tests, about 12 Gb is probably enough
- For look-up tests, 64Gb is required now

We also need to test on two different compilers, since we often have trouble tracking compiler-specific changes:
- clang (14 will work)
- gcc

Add a tag to run it on aws.
runs-on: ["self-hosted", "aws_autoscaling"]

**Comment by nkaskov** [comment]
Probably, you will need to create a couple of volumes with Boost installed from source, which will be attached to the machine every time we run tests.

Also, please check if we can use ccache for optimizing builds in the same way.
