### ISSUE TITLE
Update FRI and LPC commitment schemes

### ISSUE THREAD

**Issue by nkaskov** [NilFoundation/crypto3-zk#52]

**Comment by Zerg1996** [comment]
- [ ] Make type dependence between types in fri class and his algorithms. For example: this type in class 
https://github.com/NilFoundation/crypto3-zk/blob/25e2e9053506e9fce11798942a833b40973b433a/include/nil/crypto3/zk/commitments/detail/polynomial/basic_fri.hpp#L132
same as in proof_eval
https://github.com/NilFoundation/crypto3-zk/blob/25e2e9053506e9fce11798942a833b40973b433a/include/nil/crypto3/zk/commitments/detail/polynomial/basic_fri.hpp#L401 so suggest use smth like `typename FRI::round_proof::colinear_value_t VARIABLE_NAME` 

- [ ] Look at [TODO in code](https://github.com/NilFoundation/crypto3-zk/blob/25e2e9053506e9fce11798942a833b40973b433a/include/nil/crypto3/zk/commitments/detail/polynomial/basic_fri.hpp#L623) and solve them. For this TODO - it will be perfect to modify `proof_eval` function, that can process V as one value (So we can remove copy-value and win with mem and speed). 

- [ ] Another TODO (it will be possible to describe what needs to be done in each case...)
