### ISSUE TITLE
file include/nil/crypto3/zk/snark/arithmetization/variable.hpp does not exists

### ISSUE THREAD

**Issue by NoamDev** [NilFoundation/crypto3-zk#60]
it is required in here:
https://github.com/NilFoundation/crypto3-zk/blob/12e495ace628477bed03ea438f3f5de595c4e8fa/include/nil/crypto3/zk/snark/arithmetization/constraint_satisfaction_problems/r1cs.hpp#L40

**Comment by nkaskov** [comment]
The file has been moved math/linear_variable.hpp .

Further work on updating usage of variable type should be done in #65
